# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-08-13 16:08+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: myenv/lib/python3.12/site-packages/django_otp/forms.py:60
msgid "Please enter your OTP token."
msgstr ""

#: myenv/lib/python3.12/site-packages/django_otp/forms.py:61
#, python-brace-format
msgid "Error generating challenge: {0}"
msgstr ""

#: myenv/lib/python3.12/site-packages/django_otp/forms.py:62
msgid "The selected OTP device is not interactive"
msgstr ""

#: myenv/lib/python3.12/site-packages/django_otp/forms.py:63
#, python-brace-format
msgid "OTP Challenge: {0}"
msgstr ""

#: myenv/lib/python3.12/site-packages/django_otp/forms.py:65
msgid "Invalid token. Please make sure you have entered it correctly."
msgstr ""

#: myenv/lib/python3.12/site-packages/django_otp/forms.py:68
#, python-format
msgid ""
"Verification temporarily disabled because of %(failure_count)d failed "
"attempt, please try again soon."
msgid_plural ""
"Verification temporarily disabled because of %(failure_count)d failed "
"attempts, please try again soon."
msgstr[0] ""
msgstr[1] ""

#: myenv/lib/python3.12/site-packages/django_otp/forms.py:73
msgid "Verification of the token is currently disabled"
msgstr ""

#: myenv/lib/python3.12/site-packages/django_otp/plugins/otp_email/models.py:105
msgid "sent by email"
msgstr ""

#: myenv/lib/python3.12/site-packages/django_otp/templates/otp/admin111/login.html:38
msgid "Please correct the error below."
msgstr ""

#: myenv/lib/python3.12/site-packages/django_otp/templates/otp/admin111/login.html:38
msgid "Please correct the errors below."
msgstr ""

#: myenv/lib/python3.12/site-packages/django_otp/templates/otp/admin111/login.html:54
#, python-format
msgid ""
"You are authenticated as %(username)s, but are not authorized to access this "
"page. Would you like to login to a different account?"
msgstr ""

#: myenv/lib/python3.12/site-packages/django_otp/templates/otp/admin111/login.html:74
msgid "OTP Device:"
msgstr ""

#: myenv/lib/python3.12/site-packages/django_otp/templates/otp/admin111/login.html:79
msgid "OTP Token:"
msgstr ""

#: myenv/lib/python3.12/site-packages/django_otp/templates/otp/admin111/login.html:84
msgid "Forgotten your password or username?"
msgstr ""

#: myenv/lib/python3.12/site-packages/django_otp/templates/otp/admin111/login.html:88
msgid "Log in"
msgstr ""

#: myenv/lib/python3.12/site-packages/django_otp/templates/otp/admin111/login.html:90
msgid "Get OTP Challenge"
msgstr ""
